#ifndef PROTOCOL_H
#define PROTOCOL_H

#define PUERTO 5000
#define MAX_CLIENTES 2
#define BUFFER_SIZE 1024

/* Respuestas de autenticación */
#define RESP_LOGIN_OK "LOGIN_OK"
#define RESP_LOGIN_FAIL "LOGIN_FAIL"
#define RESP_REGISTER_OK "REGISTER_OK"
#define RESP_REGISTER_FAIL "REGISTER_FAIL"

/* Respuestas de error */
#define RESP_ERROR_INVALID_FORMAT "ERROR INVALID_FORMAT"
#define RESP_ERROR_INVALID_COMMAND "ERROR INVALID_COMMAND"
#define RESP_ERROR_USER_EXISTS "ERROR USER_EXISTS"
#define RESP_ERROR_INVALID_WORD "ERROR INVALID_WORD"
#define RESP_ERROR_AUTH_REQUIRED "ERROR AUTH_REQUIRED"
#define RESP_ERROR_NOT_YOUR_TURN "ERROR NOT_YOUR_TURN"

/* Respuestas de sesión */
#define RESP_WAITING_PLAYER "WAITING_PLAYER"
#define RESP_OPPONENT_DISCONNECTED "OPPONENT_DISCONNECTED"
#define RESP_START_GAME "START_GAME"

/* Respuestas de juego */
#define RESP_YOUR_TURN_SETWORD "YOUR_TURN_SETWORD"
#define RESP_YOUR_TURN_GUESS "YOUR_TURN_GUESS"
#define RESP_RESULT_PREFIX "RESULT"
#define RESP_ROUND_END "ROUND_END"
#define RESP_GAME_OVER_BOTH "GAME_OVER BOTH"
#define RESP_GAME_OVER_J1 "GAME_OVER J1"
#define RESP_GAME_OVER_J2 "GAME_OVER J2"
#define RESP_GAME_OVER_NONE "GAME_OVER NONE"

/* Comandos del cliente */
#define CMD_LOGIN "LOGIN"
#define CMD_REGISTER "REGISTER"
#define CMD_DISCONNECT "DISCONNECT"
#define CMD_SETWORD "SETWORD"
#define CMD_GUESS "GUESS"

#endif