#ifndef PROTOCOL_H
#define PROTOCOL_H

#define PUERTO 5000
#define MAX_CLIENTES 2
#define BUFFER_SIZE 1024

#define RESP_LOGIN_OK "LOGIN_OK"
#define RESP_LOGIN_FAIL "LOGIN_FAIL"
#define RESP_REGISTER_OK "REGISTER_OK"
#define RESP_REGISTER_FAIL "REGISTER_FAIL"
#define RESP_ERROR_INVALID_FORMAT "ERROR INVALID_FORMAT"
#define RESP_ERROR_INVALID_COMMAND "ERROR INVALID_COMMAND"
#define RESP_ERROR_USER_EXISTS "ERROR USER_EXISTS"
#define RESP_WAITING_PLAYER "WAITING_PLAYER"
#define RESP_OPPONENT_DISCONNECTED "OPPONENT_DISCONNECTED"
#define RESP_START_GAME "START_GAME"

#define CMD_LOGIN "LOGIN"
#define CMD_REGISTER "REGISTER"
#define CMD_DISCONNECT "DISCONNECT"

#endif